### ISSUE TITLE
Trigger schedule-switcher.0.onoff.0.data is active but there is no widget. Set Enabled to false!!!

### ISSUE THREAD

**Issue by schmimat** [Lucky-ESA/ioBroker.schedule-switcher#17]
**Describe the bug** 
switcher Enabled is set to false because of no widget, but there is a widget in vis-2

ERROR: _Trigger schedule-switcher.0.onoff.0.data is active but there is no widget. Set Enabled to false!!!_

**To Reproduce**  
There is no way to manual reproduce the error

**Expected behavior**  
When a widget is available and set, the switcher should not set to disable.

**Screenshots & Logfiles**  

admin.0 2024-12-15 10:32:07.697	info	==> Connected system.user.admin from 
schedule-switcher.0 2024-12-15 09:33:42.387	error	Trigger schedule-switcher.0.onoff.1.data is active but there is no widget. Set Enabled to false!!!
schedule-switcher.0 2024-12-15 09:33:42.384	error	Trigger schedule-switcher.0.onoff.0.data is active but there is no widget. Set Enabled to false!!!
schedule-switcher.0 2024-12-15 09:33:42.367	info	Start Widget control!
web.0 2024-12-15 07:42:17.236	info	<== Disconnect system.user.admin from 

**Versions:**  
 - Adapter version: <v0.0.8>
 - JS-Controller version: <v20.18.1>
 - Node version: <10.8.2>
 - Operating system: <linux>

**Comment by Lucky-ESA** [comment]
Wie ist denn der Inhalt von schedule-switcher.0.onoff.0.views und schedule-switcher.0.onoff.1.views

Gruß//Lucky

**Comment by schmimat** [comment]
Danke für das schnelle Feedback:

schedule-switcher.0.onoff.0.view; "error": "Trigger schedule-switcher.0.onoff.0.data is active but there is no widget. Set Enabled to false!!!"
schedule-switcher.0.onoff.1.view; "error": "Trigger schedule-switcher.0.onoff.0.data is active but there is no widget. Set Enabled to false!!!"

Aber die Views sind vorhanden: siehe Bild
![2024-12-18 08_52_58-Editor vis](https://github.com/user-attachments/assets/69aa778c-f021-4714-aa86-4ebf99dfd06a)



Vielen Dank für deine Bemühungen

Mit freundlichen Grüßen

Matthias

**Comment by Lucky-ESA** [comment]
Kannst du bitte mal von GIT laden und den Adapter im debug Modus laufen lassen. Habe die Deaktivierung ausgeschaltet damit der Adapter bei dir auch läuft.
Beim start wären dann die Zeilen wertvoll die wie folgt starten:
Path:
Folder:
Folders:
newViews:

Gruß//Lucky

**Comment by schmimat** [comment]
Hallo,

danke für die Hilfe.

Der Adapter funktioniert bei mir auch einige Zeit, wenn ich ihn manuell auf active setzte.

Nur wird der Active Status aus mir nicht bekannten Gründen irgendwann zurückgesetzt.

![2024-12-18 13_03_22-logs - 133-ioBroker](https://github.com/user-attachments/assets/88bbf016-7f66-4e88-b7a6-a946429326a0)

**Comment by schmimat** [comment]
Hier noch die notwendigen Infos aus deiner Anfrage:
![2024-12-18 13_16_57-logs - 133-ioBroker](https://github.com/user-attachments/assets/5b35dabe-bc1e-42d0-bc05-6d81986910c4)

Ich hoffe ein Screenshot ist in Ordnung?

**Comment by schmimat** [comment]
Beim jetzigen Neustart hat er zusätzlich die Warnung der fehlenden Views gezeigt.

![image](https://github.com/user-attachments/assets/6a192321-254e-4ee9-8fed-571ef689eeae)

**Comment by schmimat** [comment]
Sorry, was mir gerade noch eingefallen ist, ich habe das Verzeichnis manuell anlegen müssen, um den Adapter starten zu können.
![2024-12-18 13_32_12-pve-da-Heating - Proxmox Virtual Environment](https://github.com/user-attachments/assets/7fe5876e-dfdb-45cc-96bd-255d80739eba)

**Comment by Lucky-ESA** [comment]
Oha, du bist mit root eingeloggt. Mit was für ein System bist du unterwegs. Raspberry oder andere Hardware.
Kannst du mir vielleicht sagen wo deine Files liegen. Das müsste so aussehen....Daher funktioniert es bei dir auch nicht.
![Screenshot 2024-12-18 134332](https://github.com/user-attachments/assets/7aa03746-dd3a-40f6-be25-43610ac1e685)

**Comment by schmimat** [comment]
ioBorker auf Debian im LXC Container auf einem Proxmox Server (Hardware NUC)

![image](https://github.com/user-attachments/assets/215c57bd-a232-4321-8658-92ab468b7677)

Ist schon das gleiche Verzeichnis, nur ist dieses Verzeichnis bei mir leer.
Ich such mal, wo die Projekte bei mir gespeichert sind.

**Comment by Lucky-ESA** [comment]
Kannst du erneut von GIT laden und mir die Ausgabe (in debug Modus) vom Path zeigen. Fängt an mit:
RealPath:

**Comment by schmimat** [comment]
![image](https://github.com/user-attachments/assets/07c03887-7252-426d-b364-0a00e050dc07)

**Comment by schmimat** [comment]
Und zusätzlich habe ich noch alle Objekte und Files auf der Redis Datenbank.
Ich weiß, mit Kanonen auf Spatzen ..., aber es mach Spaß.

![image](https://github.com/user-attachments/assets/3566b27a-fbbf-4e34-bc00-018e23f65a65)

**Comment by schmimat** [comment]
Nein, gibt keine Files. Sorry, dass mir diese Info erst jetzt einfällt.

**Comment by schmimat** [comment]
Hier ist das Log vom laden.

[logs - 135-ioBroker.log](https://github.com/user-attachments/files/18183992/logs.-.135-ioBroker.log)

**Comment by schmimat** [comment]
Danke für die Hilfe.

**Comment by Lucky-ESA** [comment]
Kannst du bitte erneut von GIT laden und mir den Inhalt zeigen. Fängt an mit
Dir:

**Comment by schmimat** [comment]
`Dir: [{"file":"main","stats":{},"isDir":true},{"file":"vis-common-user.css","stats":{"size":3796},"isDir":false,"acl":{"owner":"system.user.admin","ownerGroup":"system.group.administrator","permissions":1632,"read":true,"write":true},"modifiedAt":1732275118432}]`

![image](https://github.com/user-attachments/assets/431efdf9-09f4-43c3-ab06-5cd4cee86734)

**Comment by Lucky-ESA** [comment]
Bitte erneut runterladen und schauen, ob sich die Objecte xxx.views nun füllen.
Danke für diesen Issue und für deine Zeit.

Gruß//Lucky

**Comment by schmimat** [comment]
Hallo ,guten Abend,

sorry für die späte Antwort, aber mein Router (UDM Unifi) hat gemeint er müsste alles vergessen und auch das Backup nicht akzeptieren.

![image](https://github.com/user-attachments/assets/bb1de663-c716-4cbc-9848-7611f2953ba9)

Schaut für mein Verständnis gut aus.

Danke für die schnelle und gute Hilfe.

**Comment by Lucky-ESA** [comment]
Sieht gut aus. Issue ist dann mit der 0.0.9 gefixt.
